name: Test
run-name: Test ${{github.sha}}

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run vcpkg
        uses: johnwason/vcpkg-action@v4
        with:
          pkgs: catch2

      - name: Configure
        run: cmake . -B build

      - name: Build
        run: cmake --build build --target merak16_asm_test

      - name: Test
        run: build/merak16_asm_test
